### ISSUE TITLE
The performance on the ScanRefer dataset

### ISSUE THREAD

**Issue by WaylonZhangW** [MrZilinXiao/SAT-Advanced#1]
Hi, Have you tried to train the SAT model on the Scanref dataset? and any tips to achieve the comparable performance shown in the paper are helpful to me. 
Appreciate it and hope to get a response  from you!

**Comment by MrZilinXiao** [comment]
Sorry for the late reply. And unfortunately, I am not following SAT for future work and I only conduct exps on Nr3D.
